### ISSUE TITLE
[Bug - models]

### ISSUE THREAD

**Issue by neptunespearz** [Traben-0/Entity_Model_Features#102]
**Describe the bug**
Several enchantment table effect resource packs are broken. These did not display the animated models at all EMF 0.2.13 but now just shows bugged models. The packs integrates the effects (floating symbols) with the model of the book. When I first loaded them, the books texture was swapped with the lectern and the enchanting effects also rendered on the lectern. It suddenly swapped back after I messed around with some files a bit thinking it was an issue with my other resource packs, but still bugged.

**Expected behavior**
In links

**Screenshots**
The book cover is facing the opposite direction of pages in all of them. All effects are suppose to be emissive but aren't, arcane enchanting table (pic1) has some specks of light on the symbols. MC reimagined (pic3) is just an updated version of Enchanting reimagined (pic2), but shows an overly large model.
https://www.curseforge.com/minecraft/texture-packs/arcane-enchanting-book
<img width="960" alt="Screen Shot 2566-09-09 at 10 08 24 PM" src="https://github.com/Traben-0/Entity_Model_Features/assets/143643017/6f758e97-bf1b-4b15-968a-5965b3444949">

https://www.curseforge.com/minecraft/texture-packs/enchanting-reimagined
<img width="960" alt="Screen Shot 2566-09-09 at 10 05 42 PM" src="https://github.com/Traben-0/Entity_Model_Features/assets/143643017/78ff8ff6-9594-48d7-85da-e50ef501e367">

https://www.curseforge.com/minecraft/texture-packs/minecraft-reimagined
<img width="960" alt="Screen Shot 2566-09-09 at 10 06 43 PM" src="https://github.com/Traben-0/Entity_Model_Features/assets/143643017/fd18131a-5e47-4509-9de3-4bb04d7bb199">

**(please complete the following information):**
 - Minecraft Version: 1.20.1
 - EMF version: RC.1
 - ETF: 4.5.1

**Comment by Traben-0** [comment]
fixed for rc 2

**Comment by neptunespearz** [comment]
wow so fast! for some reason this and a few other emissive entity models aren't emissive when I'm using shaders (iris and complementary v4). Is there any way to fix this? thankyou

**Comment by TBlazeWarriorT** [comment]
> wow so fast! for some reason this and a few other emissive entity models aren't emissive when I'm using shaders (iris and complementary v4). Is there any way to fix this? thankyou

Complementary v4 is massively outdated, and Complementary in general has its own emissiveness system.
Maybe update it, set RP mode to basic, and come back with the results?

**Comment by TBlazeWarriorT** [comment]
Issue persists with and without shaders on EMF 1.2.1. The model looks perfect on Blockbench.
Does not render with Easy Magic installed, but I could swear sometimes it renders...

(clean install for testing:)
embeddium-0.2.13+mc1.20.1.jar
entity_model_features_forge_1.20.1-1.2.1.jar
entity_texture_features_forge_1.20.1-5.1.jar
oculus-mc1.20.1-1.6.13.jar
§aReimagined§0_§8[v1.42.2]§0.zip
![image](https://github.com/Traben-0/Entity_Model_Features/assets/25572454/0f46d34b-f8c7-4091-ad6d-7ad8453f61df)

**Comment by TBlazeWarriorT** [comment]
Disabling enchanting_table_book_e.png and its .mcmeta seems to fix most if not all of the rendering issues on the latest version of EMF. The issue is on the emissive part of the rendering
Now to figure out if I can get this thing working with Easy Magic or if I'll have to annoy one of the two devs with this too 🤣 
![image](https://github.com/Traben-0/Entity_Model_Features/assets/25572454/a8b77280-1a2b-46c3-bf4f-38fb23afb0f3)
