### ISSUE TITLE
[Bug - models] EMF doesn't support texture file path in .jem files properly. Optifine compatibility issue.

### ISSUE THREAD

**Issue by magmamir** [Traben-0/Entity_Model_Features#266]
**Describe the bug**
EMF doesn't properly support [Optifine file paths](https://optifine.readthedocs.io/syntax.html#paths-file-locations) in .jem files for the "texture" field. This means that setting the "texture" parameter to `"texture": "./textures/blastling.png"` or even `"texture": "./blastling.png"` causes the mod to load the model without a texture. It seems that EMF only loads textures when the "texture" parameter has no slashes and points to a texture in the same folder as the model, like `"texture": "blastling.png"`. 

This creates a compatibility issue, as Optifine loads textures located in the same folder as the model only when the "texture" parameter includes "./". 

As a result:
- A model with `"texture": "blastling.png"` will never have a texture with Optifine.
- A model with `"texture": "./blastling.png"` will never have a texture with EMF.

Additionally, EMF doesn't support placing model textures in subfolders, whereas Optifine supports this feature.

**List and link to broken resourcepacks**
[resourcepack.zip](https://github.com/user-attachments/files/17002468/testtesttest2222.zip)

**Screenshots**
With Optifine: ![With Optifine](https://github.com/user-attachments/assets/27243512-65fd-4644-95a0-66bcb4a5a735)
With EMF: ![With EMF](https://github.com/user-attachments/assets/d2c10457-0813-4913-b30e-9163409e72f4)

**Versions**
 - Minecraft Version: 1.21
 - EMF version: 2.2.5
 - ETF version: 6.2.4

**Comment by Traben-0** [comment]
seems i forgot to actually remove the `./`  and `~/`  when they were used, so it checks for  `minecraft:optifine/cem/./textures/blastling.png` whoops

**Comment by Traben-0** [comment]
![image](https://github.com/user-attachments/assets/2ae563a5-7a38-4044-ba54-4965afe7572a)
can you double check that

**Comment by Traben-0** [comment]
thats a direct confliction of the optifine spec for cem textures 
![image](https://github.com/user-attachments/assets/3f305f3e-21ef-4d7a-8e55-1e6ef89edb7e)

**Comment by Traben-0** [comment]
assuming the texture is ofcourse next to the model

**Comment by Traben-0** [comment]
![2024-09-15_00 47 22](https://github.com/user-attachments/assets/b6d9ac59-2dc5-4977-ab08-d34d2a6d28d1)
fixed for next update

**Comment by magmamir** [comment]
Oh, it seems that both `blastling.png` and `./blastling.png` work in Optifine 1.21-pre9. My bad. There used to be a long-standing bug where textures without "./" wouldn’t load in Optifine, so I thought it was still an issue. 

Anyway, thank you for the quick fix!

**Comment by magmamir** [comment]
Fixed in the newest version.
